Added installing groups, and added the dotnetcore group. Remind user to set correct keyboard settings

diff --git a/UNIX/lib/functions b/UNIX/lib/functions
--- a/UNIX/lib/functions
+++ b/UNIX/lib/functions
@@ -15,6 +15,7 @@
 # - urf_sudocp: copy file from source to target with sudo writes
 # - urf_sudoecho: echo a text to a file with sudo
 # - urf_contains: does one string contain another
+# - urf_containsarray: does array contain string
 # - urf_check_sanity: check if system is properly setup
 # - urf_check_hostname: setup hostname if not set before
 # - urf_set_hostname: set hostname
@@ -31,39 +32,39 @@
 
 urf_ln() {
     if [ ! -L "$2" ] || [ "$(readlink "$2")" != "$1" ]; then
-	_source=${1//~/\~}
-	_target=${2//~/\~}
-	
-	echo "Symlinking: '$_source' -> '$_target'."
+	      _source=${1//~/\~}
+	      _target=${2//~/\~}
+	      
+	      echo "Symlinking: '$_source' -> '$_target'."
 
-	if [ -e "$2" ]; then
-	    if [ -L "$2" ]; then
-		echo $(urf_bold "[Symlink] '$_target' points to -> '$(readlink "$2")'")
-	    elif [ -d "$2" ]; then
-		echo $(urf_bold "[Dir] '$_target' contains: ")$(ls "$2")
-	    elif [ -f "$2" ]; then
-		echo $(urf_bold "[File] '$_target' contents: ")
-		head -3 "$2" | LC_ALL=C cut -c 1-240
+	      if [ -e "$2" ]; then
+	          if [ -L "$2" ]; then
+		            echo $(urf_bold "[Symlink] '$_target' points to -> '$(readlink "$2")'")
+	          elif [ -d "$2" ]; then
+		            echo $(urf_bold "[Dir] '$_target' contains: ")$(ls "$2")
+	          elif [ -f "$2" ]; then
+		            echo $(urf_bold "[File] '$_target' contents: ")
+		            head -3 "$2" | LC_ALL=C cut -c 1-240
             fi
-	    if ! urf_yNprompt "Target Exists! Overwrite existing '$_target'? (y/N)"; then
-		echo $(urf_bold "Target Left Alone! Fix destination or Run again.")
-		return 1
-	    fi
-	fi
-	
-	# Create parent directories if required
-	mkdir -p "${2%/*}"
-	# Remove existing files if present
-	rm -rf "$2"
-	case $WHARDWARE in
-	(Linux*)
-            ln -Ffs "$1" "$2"
-            ;;
-	(Darwin*)
-            ln -Ffhs "$1" "$2"
-	esac
-	
-	unset _source _target
+	          if ! urf_yNprompt "Target Exists! Overwrite existing '$_target'? (y/N)"; then
+		            echo $(urf_bold "Target Left Alone! Fix destination or Run again.")
+		            return 1
+	          fi
+	      fi
+	      
+	      # Create parent directories if required
+	      mkdir -p "${2%/*}"
+	      # Remove existing files if present
+	      rm -rf "$2"
+	      case $WHARDWARE in
+	          (Linux*)
+                ln -Ffs "$1" "$2"
+                ;;
+	          (Darwin*)
+                ln -Ffhs "$1" "$2"
+	      esac
+	      
+	      unset _source _target
     fi
 }
 
@@ -71,32 +72,32 @@ urf_cprepo() {
     # Check if file exists in storage
     WHICH_FILE=$(urf_repofile $1)
     if [ -z "$WHICH_FILE" ]; then
-	echo "Copy: File $1 does not exist in storage."
-	exit 2
+	      echo "Copy: File $1 does not exist in storage."
+	      exit 2
     elif [ ! -L "$2" ]; then
-	if [ -e "$2" ]; then
-	    echo "Copy: Replace file/dir with file/folder at: $1."
-	else
-	    echo "Copy: '$1' -> '$2'."
-	fi
+	      if [ -e "$2" ]; then
+	          echo "Copy: Replace file/dir with file/folder at: $1."
+	      else
+	          echo "Copy: '$1' -> '$2'."
+	      fi
     fi
     # Could integrate urf_lnrepo and urf_cprepo some time
     # Copy file
     case $3 in
-    (-sudo)
-        # Create parent directories if required
-        sudo mkdir -p "${2%/*}"
-        # Remove existing files if present
-        sudo rm -rf "$2"
-	sudo cp -rf "$WHICH_FILE" "$2"
-	;;
-    (*)
-        # Create parent directories if required
-        mkdir -p "${2%/*}"
-        # Remove existing files if present
-        rm -rf "$2"
-	cp -rf "$WHICH_FILE" "$2"
-	;;
+        (-sudo)
+            # Create parent directories if required
+            sudo mkdir -p "${2%/*}"
+            # Remove existing files if present
+            sudo rm -rf "$2"
+	          sudo cp -rf "$WHICH_FILE" "$2"
+	          ;;
+        (*)
+            # Create parent directories if required
+            mkdir -p "${2%/*}"
+            # Remove existing files if present
+            rm -rf "$2"
+	          cp -rf "$WHICH_FILE" "$2"
+	          ;;
     esac
 }
 
@@ -104,10 +105,10 @@ urf_lnrepo() {
     # Check if file exists in storage
     WHICH_FILE=$(urf_repofile $1)
     if [ -z "$WHICH_FILE" ]; then
-	echo "[urf_lnrepo]: '$1' not found for current device!"
-	exit 2
+	      echo "[urf_lnrepo]: '$1' not found for current device!"
+	      exit 2
     else
-	urf_ln "$WHICH_FILE" "$2"
+	      urf_ln "$WHICH_FILE" "$2"
     fi
 }
 
@@ -120,32 +121,32 @@ urf_repofile() {
     # I didn't use 'find' because then I can't $(urf_repofile emacs.d/init.el)
 
     find_file() {
-	local which_file=""
-	local max_priority=-1
-	local directories=(~/dotfiles/config ~/Dropbox/Setup/config)
-	for directory in $directories; do
-	    if [ ! -d $directory ]; then
-		continue
-	    fi
-	    for file in $directory/"${1%%\#*}"*; do
-		# Extract hardware information from file + Create regex matcher
-		local whardware="${file#*\#}"
-		local whardware_re=".*${whardware:gs/-/.*}.*"
-		
-		# Count priority (more hardware sections means more priority)
-		local priority=0
-		if urf_contains $file "#"; then
-		    ((priority=1+$(awk -F"-" '{print NF-1}' <<< "${whardware}")))
-		fi
+	      local which_file=""
+	      local max_priority=-1
+	      local directories=(~/dotfiles/config ~/Dropbox/Setup/config)
+	      for directory in $directories; do
+	          if [ ! -d $directory ]; then
+		            continue
+	          fi
+	          for file in $directory/"${1%%\#*}"*; do
+		            # Extract hardware information from file + Create regex matcher
+		            local whardware="${file#*\#}"
+		            local whardware_re=".*${whardware:gs/-/.*}.*"
+		            
+		            # Count priority (more hardware sections means more priority)
+		            local priority=0
+		            if urf_contains $file "#"; then
+		                ((priority=1+$(awk -F"-" '{print NF-1}' <<< "${whardware}")))
+		            fi
 
-		# Is compatible hardware && Has greater priority
-		if ( ! urf_contains $file "#" || [[ $WHARDWARE =~ $whardware_re ]]) && [ $priority -gt $max_priority ]; then
-		    which_file="$file"
-		    max_priority=$priority
-		fi
-	    done
-	done
-	echo "$which_file"
+		            # Is compatible hardware && Has greater priority
+		            if ( ! urf_contains $file "#" || [[ $WHARDWARE =~ $whardware_re ]]) && [ $priority -gt $max_priority ]; then
+		                which_file="$file"
+		                max_priority=$priority
+		            fi
+	          done
+	      done
+	      echo "$which_file"
     }
 
     echo "$(find_file $1)"
@@ -155,51 +156,51 @@ urf_repofile() {
 urf_namedurl() {
     local folder_=""
     case $WHARDWARE in
-    (Linux-x86*)
-	case $1 in
-	(firefox)
-	    folder_=~/.mozilla/firefox
-	    ;;
-	(fonts)
-	    folder_=~/.local/share/fonts
-	    ;;
-	(keepassxc)
-	    folder_=~/.config/keepassxc
-	    ;;
-	(config)
-	    folder_=~/.config
-	    ;;
-	(urfilez)
-	    folder_=~/.config/urfilez
-	esac
-	;;
-    (Darwin*)
-	case $1 in
-	(firefox)
-	    folder_=~/"Library/Application Support/Firefox/Profiles"
-	    ;;
-	(fonts)
-	    folder_=~/Library/Fonts
-	    ;;
-	(iTerm2)
-	    folder_=~/Dropbox/Setup/apps/iTerm2
-	    ;;
-	(keepassxc)
-	    folder_=~/"Library/Application Support/keepassxc"
-	    ;;
-	(config)
-	    folder_=~/"Library/Application Support"
-	    ;;
-	(urfilez)
-	    folder_=~/"Library/Application Support/urfilez"
-	esac
+        (Linux-x86*)
+	          case $1 in
+	              (firefox)
+	                  folder_=~/.mozilla/firefox
+	                  ;;
+	              (fonts)
+	                  folder_=~/.local/share/fonts
+	                  ;;
+	              (keepassxc)
+	                  folder_=~/.config/keepassxc
+	                  ;;
+	              (config)
+	                  folder_=~/.config
+	                  ;;
+	              (urfilez)
+	                  folder_=~/.config/urfilez
+	          esac
+	          ;;
+        (Darwin*)
+	          case $1 in
+	              (firefox)
+	                  folder_=~/"Library/Application Support/Firefox/Profiles"
+	                  ;;
+	              (fonts)
+	                  folder_=~/Library/Fonts
+	                  ;;
+	              (iTerm2)
+	                  folder_=~/Dropbox/Setup/apps/iTerm2
+	                  ;;
+	              (keepassxc)
+	                  folder_=~/"Library/Application Support/keepassxc"
+	                  ;;
+	              (config)
+	                  folder_=~/"Library/Application Support"
+	                  ;;
+	              (urfilez)
+	                  folder_=~/"Library/Application Support/urfilez"
+	          esac
     esac
 
     # DEFINED ----------------------------------------------------------------------
     if [ ! -z $folder_ ]; then
-	echo $folder_
-	unset folder_
-	return 0
+	      echo $folder_
+	      unset folder_
+	      return 0
     fi
 
     # UNDEFINED --------------------------------------------------------------------
@@ -208,10 +209,10 @@ urf_namedurl() {
     # REQUIRED
     local required=(firefox fonts iterm)
     for key in $required; do
-	if [ $1 = $key ]; then
-	    echo $(urf_bold "[wfolder] ERROR: '$1' should be defined!")
-	    exit 1
-	fi
+	      if [ $1 = $key ]; then
+	          echo $(urf_bold "[wfolder] ERROR: '$1' should be defined!")
+	          exit 1
+	      fi
     done
 
     # OPTIONAL, although it is weird the key was called
@@ -222,26 +223,26 @@ urf_sync() {
     # How do I add apps to the dock? / Remove exising ones?
 
     case $1 in
-    (-b|--backup)
-	pyenv versions --bare --skip-aliases | grep -v env | grep -v system > $(urf_repofile pyenv_versions)
-	;;
-    (-r|--restore)
-	while read pyenv_version; do
-	    pyenv install -s $pyenv_version
-	done < $(urf_repofile pyenv_versions)
-	;;
-    (*)
-	echo "Backup (-b|--backup) or restore (-r|--restore)?"
-	exit
-	;;
+        (-b|--backup)
+	          pyenv versions --bare --skip-aliases | grep -v env | grep -v system > $(urf_repofile pyenv_versions)
+	          ;;
+        (-r|--restore)
+	          while read pyenv_version; do
+	              pyenv install -s $pyenv_version
+	          done < $(urf_repofile pyenv_versions)
+	          ;;
+        (*)
+	          echo "Backup (-b|--backup) or restore (-r|--restore)?"
+	          exit
+	          ;;
     esac
 
     case $WHARDWARE in
-    (Linux-x86*)
-	# Linux Desktop environment synchronization scripts
-	# If file doesn't exist, it isn't loaded
-	source sync-$WDE $1 2>/dev/null
-	;;
+        (Linux-x86*)
+	          # Linux Desktop environment synchronization scripts
+	          # If file doesn't exist, it isn't loaded
+	          source sync-$WDE $1 2>/dev/null
+	          ;;
     esac
 }
 
@@ -258,11 +259,11 @@ urf_yNprompt() {
     read -r prompt_ans\?">> $1 "
 
     if [ ! -z $prompt_ans ] && [ ! -z $prompt_ans ]; then
-	prompt_ans=$(python -c "print('$prompt_ans'.lower())" )
+	      prompt_ans=$(python -c "print('$prompt_ans'.lower())" )
     fi
     local default_ans="y"
     if [[ "$1" = *"(y/N)"* ]]; then
-	default_ans="n"
+	      default_ans="n"
     fi
     if ([ $default_ans = "y" ] && [ -z $prompt_ans ]) || ([ $prompt_ans = "y" ]) &>/dev/null ; then
         return 0
@@ -278,7 +279,7 @@ urf_bold() {
 
 urf_btitle() {
     if [ ! -z $2 ]; then
-	echo $(urf_bold $1):$2
+	      echo $(urf_bold $1):$2
     fi
 }
 
@@ -290,39 +291,39 @@ urf_setup_whoami() {
 
     # Package manager
     if type apt-get &> /dev/null; then
-	export WPKG=apt-get;
+	      export WPKG=apt-get;
     elif type brew &> /dev/null || [ $WKERNEL = "Darwin"]; then
-	export WPKG=brew;
+	      export WPKG=brew;
     elif type yum &> /dev/null; then
-	export WPKG=yum;
+	      export WPKG=yum;
     elif type dnf &> /dev/null; then
-	export WPKG=dnf;
+	      export WPKG=dnf;
     fi
 
     # Hey you know what.. we could place $WDE and $WDISTRO inside WKERNEL? Rename it to WHARDWARE
     case $WKERNEL in
-    (Darwin)
-    ;;
-    (Linux)
-	# Desktop Environment (DE)
-	if urf_contains $XDG_CURRENT_DESKTOP:l gnome; then
-	    export WDE=gnome;
-	elif urf_contains $XDG_CURRENT_DESKTOP:l kde; then
-	    export WDE=kde;
-	fi
+        (Darwin)
+        ;;
+        (Linux)
+	          # Desktop Environment (DE)
+	          if urf_contains $XDG_CURRENT_DESKTOP:l gnome; then
+	              export WDE=gnome;
+	          elif urf_contains $XDG_CURRENT_DESKTOP:l kde; then
+	              export WDE=kde;
+	          fi
 
-	# TODO: might slow down terminal - look for alternative
-	local lsb_release=$(lsb_release -d)
-	if urf_contains $lsb_release:l "fedora"; then
-	    export WDISTRO=Fedora;
-	elif urf_contains $lsb_release:l "ubuntu"; then
-	    export WDISTRO=Ubuntu;
-	elif urf_contains $lsb_release:l "raspbian"; then
-	    export WDISTRO=Raspbian;
-	fi
-	;;
-    (*)
-	echo ($urf_bold "WKERNEL='$WKERNEL' not supported!")
+	          # TODO: might slow down terminal - look for alternative
+	          local lsb_release=$(lsb_release -d)
+	          if urf_contains $lsb_release:l "fedora"; then
+	              export WDISTRO=Fedora;
+	          elif urf_contains $lsb_release:l "ubuntu"; then
+	              export WDISTRO=Ubuntu;
+	          elif urf_contains $lsb_release:l "raspbian"; then
+	              export WDISTRO=Raspbian;
+	          fi
+	          ;;
+        (*)
+	          echo ($urf_bold "WKERNEL='$WKERNEL' not supported!")
     esac
 
     # Host name (could be function)
@@ -344,9 +345,9 @@ urf_sudocp() {
     # 1: copy this file
     # 2: to this file
     if [ $3 = "-a" ]; then
-	cat "$1" | sudo tee -a "$2" >> /dev/null
+	      cat "$1" | sudo tee -a "$2" >> /dev/null
     else
-	cat "$1" | sudo tee "$2" >> /dev/null
+	      cat "$1" | sudo tee "$2" >> /dev/null
     fi
 }
 
@@ -354,9 +355,9 @@ urf_sudoecho() {
     # 1: save this text
     # 2: to this file
     if [ "$3" = "-a" ]; then
-	echo "$1" | sudo tee -a "$2" >> /dev/null
+	      echo "$1" | sudo tee -a "$2" >> /dev/null
     else
-	echo "$1" | sudo tee "$2" >> /dev/null
+	      echo "$1" | sudo tee "$2" >> /dev/null
     fi
 }
 
@@ -371,13 +372,19 @@ urf_contains() {
     fi
 }
 
+urf_containsarray() {
+    haystack=$1
+    needle=$2
+    [ -n $needle ] && [[ ${haystack[(i)$needle]} -le ${#haystack} ]]
+}
+
 urf_check_sanity() {
     local required_dirs=(~/Dropbox/Setup/config)
     for dir in $required_dirs; do
-	if [ ! -d $dir ]; then
-	    echo $(urf_bold "Missing directory: $dir")
-	    return 1
-	fi
+	      if [ ! -d $dir ]; then
+	          echo $(urf_bold "Missing directory: $dir")
+	          return 1
+	      fi
     done
 
     # Add install scripts to path if first install (normally in .zshenv)
@@ -392,7 +399,7 @@ urf_check_sanity() {
     # Config folder
     local config_url=$(urf_namedurl urfilez)
     if [ ! -f $config_url ]; then
-	    mkdir -p $config_url
+	      mkdir -p $config_url
     fi
 
     # TODO: maybe not required
@@ -417,17 +424,17 @@ urf_set_hostname() {
     read hostname
     echo $hostname > $hostname_url
     case $WKERNEL in
-    (Darwin)
-        # Set computer name (as done via System Preferences → Sharing)
-        sudo scutil --set ComputerName $hostname
-        sudo scutil --set HostName $hostname
-        sudo scutil --set LocalHostName $hostname
-        sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string $hostname
-        ;;
-    (Linux)
-        urf_sudoecho $hostname /etc/hostname
-        # TODO: modify /etc/hosts too (if old hostname is there!)
-        ;;
+        (Darwin)
+            # Set computer name (as done via System Preferences → Sharing)
+            sudo scutil --set ComputerName $hostname
+            sudo scutil --set HostName $hostname
+            sudo scutil --set LocalHostName $hostname
+            sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string $hostname
+            ;;
+        (Linux)
+            urf_sudoecho $hostname /etc/hostname
+            # TODO: modify /etc/hosts too (if old hostname is there!)
+            ;;
     esac
 
     # Read current hostname ask see if need to restart
@@ -462,7 +469,7 @@ urf_set_repos() {
     local config_url=$(urf_namedurl urfilez)
     
     local repos_url=$config_url/repos
-	echo -n "Enter desired folder repositories from highest to lowest priority (one per line): "
+	  echo -n "Enter desired folder repositories from highest to lowest priority (one per line): "
     cat > $repos_url
 
     echo "It is recommended to run urf (urfilez run) now to update the files from the new repositories."
@@ -472,9 +479,9 @@ urf_arraywrite() {
     # 1: filename
     # 2: an array to write
     for entry in $@; do
-	if [ $entry != $1 ]; then
-	    echo $entry
-	fi
+	      if [ $entry != $1 ]; then
+	          echo $entry
+	      fi
     done > $1
 }
 
@@ -482,7 +489,7 @@ urf_arrayread() {
     # 1: filename
     read_array=()
     for line in "${(@f)"$(<$1)"}"; do
-	read_array+=("$line")
+	      read_array+=("$line")
     done
     echo $read_array
 }
